apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: demo-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-test 
  name: demo-test
  namespace: demo-test
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-test
    weight: 100 
